modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Automatic sawmill addon for TerraFirmaCraft with mechanical power and soft integrations.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc_debark"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc_lumberjack"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc_items"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc_metal_tools"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
